// EnginotechC++ — Arduino Sketch Builder Implementation (revised)
// Assembles the top-level structure of an Arduino .ino sketch.
//
// Architecture (one file per responsibility):
//   shim.h / shim.cpp      — runtime bridge to Arduino APIs
//   expr_emitter.h/.cpp    — expression → Arduino C++ text
//   stmt_emitter.h/.cpp    — statement → Arduino C++ text
//   sketch_builder.h/.cpp  — orchestrate full .ino output

#include "sketch_builder.h"
#include <algorithm>
#include <set>

namespace eng {
namespace arduinogen {

// ── shim text (inlined; also available as separate shim.h) ───────
static const char* SHIM_TEXT = R"(// ---- EnginotechC++ embedded shim (do not edit) ----
#include <Arduino.h>

// Output pin — mirrors eng::embedded::gpio::OutputPin
struct EcOutPin {
  int pin;
  void high()      { digitalWrite(pin, HIGH); }
  void low()       { digitalWrite(pin, LOW);  }
  void toggle()    { digitalWrite(pin, digitalRead(pin) ? LOW : HIGH); }
  bool read() const { return digitalRead(pin) == HIGH; }
};

// Input pin — mirrors eng::embedded::gpio::InputPin
struct EcInPin {
  int pin;
  int read()         { return digitalRead(pin); }
  void setMode(int m){ pinMode(pin, m); }
};

// PWM pin
struct EcPwmPin {
  int pin;
  void start(int freq, int duty) {
    pinMode(pin, OUTPUT);
    analogWriteFrequency(freq);
    analogWrite(pin, duty);
  }
  void stop()    { analogWrite(pin, 0); }
  void setDuty(int d) { analogWrite(pin, d); }
};

// GPIO factory
static EcOutPin ec_gpio_output(int p)        { pinMode(p, OUTPUT); return {p}; }
static EcInPin  ec_gpio_input(int p)         { pinMode(p, INPUT);  return {p}; }
static EcInPin  ec_gpio_input_pullup(int p)  { pinMode(p, INPUT_PULLUP); return {p}; }
static EcPwmPin ec_gpio_pwm(int p)           { pinMode(p, OUTPUT); return {p}; }
// ---- end shim ----
)";

// ── cppTypeOf (shared helper) ───────────────────────────────────
static std::string cppTypeOf(const TypePtr& t) {
    if (!t) return "int";
    const std::string& n = t->getName();
    if (n == "int" || n == "INT" || n == "int8" || n == "int16" || n == "int32" ||
        n == "uint" || n == "uint8" || n == "byte")     return "int";
    if (n == "float64" || n == "float32" || n == "f64" || n == "double")
        return "double";
    if (n == "bool" || n == "BOOL")                    return "bool";
    if (n == "string" || n == "STRING")                return "String";
    if (n == "char" || n == "CHAR")                    return "char";
    return n; // pass through user types
}

// ── SketchBuilder ───────────────────────────────────────────────
SketchBuilder::SketchBuilder(std::ostringstream& out, const std::string& boardId)
    : out_(out), board_(boardId) {}

void SketchBuilder::build(const Program& prog) {
    // Partition top-level items
    const FunctionDecl* setupFn = nullptr;
    const FunctionDecl* loopFn  = nullptr;
    const FunctionDecl* mainFn  = nullptr;
    std::vector<const FunctionDecl*> helpers;

    for (const auto& item : prog.topLevel) {
        if (!item || item->kind() != StmtKind::FunctionDecl) continue;
        auto* fn = static_cast<FunctionDecl*>(item.get());
        if (fn->name == "setup")  setupFn = fn;
        else if (fn->name == "loop") loopFn = fn;
        else if (fn->name == "main") mainFn = fn;
        else                       helpers.push_back(fn);
    }

    // ── Header ──
    out_ << "// ============================================================\n";
    out_ << "// Generated by EnginotechC++ — target: Arduino";
    if (!board_.empty()) out_ << " (" << board_ << ")";
    out_ << "\n";
    out_ << "// ============================================================\n\n";
    out_ << "#include <Arduino.h>\n\n";

    // ── Shim ──
    out_ << SHIM_TEXT << "\n";

    // ── Forward declarations ──
    for (const auto* fn : helpers) {
        out_ << cppTypeOf(fn->returnType) << " " << fn->name << "(";
        for (size_t i = 0; i < fn->params.size(); ++i) {
            if (i) out_ << ", ";
            out_ << cppTypeOf(fn->params[i].second) << " " << fn->params[i].first;
        }
        out_ << ");\n";
    }
    if (!helpers.empty()) out_ << "\n";

    // ── Helper function bodies ──
    for (const auto* fn : helpers) {
        ExprEmitter expr(out_);
        StmtEmitter stmt(out_, expr);

        out_ << cppTypeOf(fn->returnType) << " " << fn->name << "(";
        for (size_t i = 0; i < fn->params.size(); ++i) {
            if (i) out_ << ", ";
            out_ << cppTypeOf(fn->params[i].second) << " " << fn->params[i].first;
        }
        out_ << ") {\n";

        // Declare parameters as variables in scope
        for (const auto& [name, type] : fn->params)
            stmt.declareVar(name, type);

        for (const auto& st : fn->body) stmt.emit(st);
        out_ << "}\n\n";
    }

    // ── Arduino main() entry point ──
    out_ << "int main() {\n";
    if (mainFn) {
        ExprEmitter expr(out_);
        StmtEmitter stmt(out_, expr);
        // Declare parameters as variables in scope
        for (const auto& [name, type] : mainFn->params)
            stmt.declareVar(name, type);
        for (const auto& st : mainFn->body) stmt.emit(st);
    } else if (setupFn || loopFn) {
        // If no explicit main(), call setup() once then loop() forever
        if (setupFn) {
            ExprEmitter expr(out_);
            StmtEmitter stmt(out_, expr);
            for (const auto& st : setupFn->body) stmt.emit(st);
        }
        out_ << "while (true) {";
        if (loopFn) {
            ExprEmitter expr(out_);
            StmtEmitter stmt(out_, expr);
            for (const auto& st : loopFn->body) stmt.emit(st);
        }
        out_ << "}";
    }
    out_ << "\n}\n\n";
}

// ── public entry point ───────────────────────────────────────────
std::string generateSketch(const Program& prog, const std::string& boardId) {
    std::ostringstream out;
    SketchBuilder builder(out, boardId);
    builder.build(prog);
    return out.str();
}

} // namespace arduinogen
} // namespace eng
